name: Zadanie 2 CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wersja aplikacji'
        required: true

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Qemu
        uses: docker/setup-qemu-action@v2

      - name: Install Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:${{ github.run_number }}
            skolimowskad/zad2gitops:latest

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: dockerCI
    steps:
      - name: Checkout Config repo
        uses: actions/checkout@v2
        with:
          repository: skolimowskad/config-repo

      - name: Configure access to Config repo
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          sed -i 's|image: skolimowskad/zad2gitops:.*|image: skolimowskad/zad2gitops:${{ github.run_number }}|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update Docker image version"
          git push https://skolimowskad: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@github.com/skolimowskad/config-repo main

