name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:latest
            skolimowskad/zad2gitops:$(date +'%Y%m%d%H%M%S')

  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "dominika.skolimowska@pollub.edu.pl"
          git config user.name "skolimowskad"

      - name: Modify Kubernetes Manifests
        run: |
          name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:latest
            skolimowskad/zad2gitops:$(date +'%Y%m%d%H%M%S')

  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "dominika.skolimowska@pollub.edu.pl"
          git config user.name "skolimowskad"

      - name: Modify Kubernetes Manifests
        run: |
          cd ./config-repo
          sed -i 's|image: skolimowskad/zad2gitops:.*|image: skolimowskad/zad2gitops:'"$(date +'%Y%m%d%H%M%S')"'|' deployment.yaml
          git add deployment.yaml
          git commit -m "Update image reference"
          git push origin main
          git push origin main
