name: Zadanie 2 CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wersja aplikacji'
        required: true

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install Qemu
        uses: docker/setup-qemu-action@v2

      - name: Install Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:${{ github.run_number }}
            skolimowskad/zad2gitops:latest

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: dockerCI
    steps:
      - name: Checkout Config repo
        uses: actions/checkout@v2
        with:
          repository: skolimowskad/config-repo
          token: ${{ secrets.TOKEN }}

      - name: Configure access to Config repo
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          # Check if there are changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            sed -i 's|image: skolimowskad/zad2gitops:.*|image: skolimowskad/zad2gitops:${{ github.run_number }}|' deployment.yaml
            git add deployment.yaml
            git commit -m "Update Docker image version"
            git push origin main
          fi
