name: Zadanie 2 CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wersja aplikacji'
        required: true

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install Qemu
        uses: docker/setup-qemu-action@v2

      - name: Install Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:${{ github.run_number }}
            skolimowskad/zad2gitops:latest

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: dockerCI
    steps:
      - name: Checkout Config repo
        uses: actions/checkout@v2
        with:
          repository: skolimowskad/config-repo
          token: ${{ secrets.TOKEN }}

      - name: Configure access to Config repo
        run: |
          gh pr comment ${{ github.event.inputs.version }} -b "Aktualizacja numeru wersji w pliku index.html"
          gh pr merge ${{ github.event.inputs.version }} -m "Merge PR: Aktualizacja numeru wersji w pliku index.html"
          git fetch origin
          git checkout -B main origin/main
          git pull origin main
          sed -i 's|Numer Wersji: .*|Numer Wersji: ${{ github.run_number }}|' index.html
          git add index.html
          git commit -m "Update version number in index.html"
          git push origin main
