name: Zadanie 2 CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wersja aplikacji'
        required: true

jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install Qemu
        uses: docker/setup-qemu-action@v2

      - name: Install Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            skolimowskad/zad2gitops:${{ github.event.inputs.version }}
            skolimowskad/zad2gitops:latest

  kubernetesCI:
    runs-on: ubuntu-latest
    needs: dockerCI
    steps:
      - name: Checkout Config repo
        uses: actions/checkout@v2
        with:
          repository: skolimowskad/config-repo
          token: ${{ secrets.TOKEN }}

      - name: Pull latest changes
        run: git pull origin main

      - name: Configure access to Config repo
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          pr_number=$(gh pr list | grep "Aktualizacja numeru wersji w pliku index.html" | awk '{print $1}')
          gh pr comment $pr_number -b "Aktualizacja numeru wersji w pliku index.html"
          gh pr merge $pr_number -m "Merge PR: Aktualizacja numeru wersji w pliku index.html"
          sed -i "s|Numer Wersji: .*|Numer Wersji: ${{ github.event.inputs.version }}|g" index.html
          git add index.html
          git commit -m "Update version number in index.html"
          git push origin main
